# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 80d1988fa8a6c117cdb2c3a29178b94dcf46571739468a7578f7a38a58be0f44708e0fd8bea6dd61861e96401cdd4d75646f1de4f48fce0834015956433932d4

test:
  secret_key_base: 780e90794c0549028513f69bb55486827dd89e2e70f6f4521d48ee2fa2a5cdc9ef0ebbe8ac6cedf3c6a1f9a325d37a6368e82eb8379e0121f0aeb39a2704769c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
