# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 110ef6e246ca0fde17651aa1dd0df95cc6e6c56837110e98715f1bda3caae4130b95845b7fcaaba172c9428470e369a4855517381e4e75987991106178389d15

test:
  secret_key_base: 657c1c4102ea5f35deb9458e5be153fb611325b73e861564076323273eef6652064d99bb3883918eb851ad417aef82c1ff9b2af9be328abc264ad8f758fa465c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
